POST /account/api/accounts
Host: localhost:1999
Content-Type: application/json

{
    "userId": "westloverock",
    "password": "westloverockPassword",
    "name": "서정석",
    "nickname": null,
    "email": "westloverock@github.com",
    "phoneNumber": null
}

###

GET /account/api/accounts/westloverock
Host: localhost:1999

###

POST /account/api/accounts/westloverock
Host: localhost:1999
Content-Type: application/json

{
  "state": "휴면"
}

###

PUT /account/api/accounts/westloverock
Host: localhost:1999
Content-Type: application/json

{
    "userId": "westloverock",
    "password": "westloverockPassword",
    "name": "서정석",
    "nickname": "서경석",
    "email": "westloverock@github.com",
    "phoneNumber": null
}

###

GET /account/api/accounts/email/westloverock@github.com
Host: localhost:1999
Content-Type: application/json

###

POST /account/api/accounts/westloverock/profile
Host: localhost:1999
Content-Type: application/json

{
  "imagePath": "/src/static/useridProfileImage"
}

###